name: AWS OIDC demo

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # <-- required for OIDC
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    environment: >
      ${{
        startsWith(github.ref, 'refs/heads/prod') && 'prod' ||
        startsWith(github.ref, 'refs/heads/release/') && 'ppe' ||
        'dev'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: show environment
        run: |
          if [[ "${{ github.ref }}" == refs/heads/prod* ]]; then
            echo "Environment: prod"
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "Environment: ppe"
          else
            echo "Environment: dev"
          fi

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        env:
          ORG_ID: ${{ secrets.ORG_ID }}
          OIDC_ROLE_NAME: ${{ secrets.OIDC_ROLE_NAME }}
          OIDC_FULL_ROLE_ARN: ${{ secrets.OIDC_FULL_ROLE }}
        with:
          role-to-assume: ${{ env.OIDC_FULL_ROLE_ARN }}
          aws-region: ap-south-1  # or your preferred region


      - name: Verify caller identity
        run: aws sts get-caller-identity

      # Example: list S3 buckets (if allowed)
      - name: List S3 buckets from account
        run: aws s3 ls
