name: AWS Infrastructure Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # <-- required for OIDC
  contents: read

jobs:
  aws-infrastructure-deployment:
    runs-on: ubuntu-latest
    environment: >
      ${{
        startsWith(github.ref, 'refs/heads/prod') && 'prod' ||
        startsWith(github.ref, 'refs/heads/release/') && 'ppe' ||
        'dev'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ORG_ID }}:role/${{ secrets.OIDC_ROLE_NAME }}
          aws-region: ap-south-1  # or your preferred region


      - name: Verify caller identity
        run: aws sts get-caller-identity

      # Example: list S3 buckets (if allowed)
      - name: List S3 buckets from account
        run: aws s3 ls
