name: AWS OIDC demo

on:
  push:
    branches:
      - main

permissions:
  id-token: write       # <-- required for OIDC
  contents: read

jobs:
  aws-test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ORG_ID }}:role/${{ secrets.ROLE_NAME }}
          aws-region: ap-south-1  # or your preferred region

      - name: Verify caller identity
        run: aws sts get-caller-identity

      # Example: list S3 buckets (if allowed)
      - name: List S3 buckets from account
        run: aws s3 ls
