name: 'Terraform Check'

on:
  pull_request:
    branches:
      - "dev"
permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: >
      ${{
        startsWith(github.ref, 'refs/heads/prod') && 'prod' ||
        startsWith(github.ref, 'refs/heads/ppe/') && 'ppe' ||
        'dev'
      }}
    env:
      TFVARS_FILE: ${{ startsWith(github.ref, 'refs/heads/prod') && 'env/prod.tfvars' || startsWith(github.ref, 'refs/heads/ppe/') && 'env/ppe.tfvars' || 'env/dev.tfvars' }}
      TF_HOME_DIR: k8s_infra/terraform/aws/
      GITHUB_TOKEN: ${{ github.token }}


    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_HOME_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.3
        terraform_wrapper: false

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform fmt (check)
      run: terraform fmt -check -diff -recursive

    # # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    # - name: Terraform init (no backend)
    #   run: terraform init -backend=false -input=false -no-color

    # # Validates the configuration files in a directory, ensuring that the directory is syntactically valid and able to be used as a configuration.
    # - name: Terraform validate
    #   run: terraform validate -no-color
      
    # Setup TFLint
    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: v0.54.0

    # Initialize TFLint
    - name: TFLint init
      run: tflint --init

    # Run TFLint
    - name: TFLint
      run: tflint --recursive

    # Optional: tfsec
    # - name: tfsec
    #   uses: aquasecurity/tfsec-action@v1.0.3
    #   with:
    #     working_directory: ${{ env.TF_HOME_DIR }}
    #     github_token: ${{ env.GITHUB_TOKEN }}
    #     additional_args: --config-file=../.tfsec.yml

    # - name: Checkov
    #   uses: bridgecrewio/checkov-action@v12
    #   with:
    #     directory: ${{ env.TF_HOME_DIR }}
    #     framework: terraform
    #     download_external_modules: true